
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1000, 'Sneakers');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1001, 'T-Shirts');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1002, 'Pants');

INSERT INTO SUPPLIER (ID, NAME) VALUES (1000, 'Nike');
INSERT INTO SUPPLIER (ID, NAME) VALUES (1001, 'Jordan');
INSERT INTO SUPPLIER (ID, NAME) VALUES (1002, 'Adidas');
INSERT INTO SUPPLIER (ID, NAME) VALUES (1003, 'Sufgang');

INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE) VALUES (1000, 'Jordan 1 Midnight Navy', 1001, 1001, 3);
INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE) VALUES (1001, 'Nike Dunk SB Court Purple', 1002, 1001, 15);
INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE) VALUES (1002, 'Cry Now Laught Later', 1003, 1002, 11);
INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE) VALUES (1003, 'Campus 80s South Park Towelie', 1003, 1001, 4);

